import type { AssessmentQuestion } from '@/lib/dal/assessment'

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'a1000000-0000-0000-0000-000000000001',
    category: 'technical',
    type: 'multiple_choice',
    prompt: 'A biological indicator (BI) for steam sterilization uses spores of which organism?',
    options_json: { A: 'Geobacillus stearothermophilus', B: 'Bacillus atrophaeus', C: 'Staphylococcus aureus', D: 'Bacillus subtilis' },
    scoring_key_json: { correct: 'A', score_map: { A: 1.0, B: 0.0, C: 0.0, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000002',
    category: 'technical',
    type: 'multiple_choice',
    prompt: 'The minimum required exposure time for a 132°C gravity steam sterilization cycle is:',
    options_json: { A: '3 minutes', B: '4 minutes', C: '10 minutes', D: '20 minutes' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.25, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000003',
    category: 'technical',
    type: 'multiple_choice',
    prompt: 'High-level disinfection (HLD) differs from sterilization in that it:',
    options_json: { A: 'Kills all microbial life including prions', B: 'Eliminates all organisms except high numbers of bacterial spores', C: 'Reduces microbial count by 99.9%', D: 'Is used for critical-class instruments only' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000004',
    category: 'technical',
    type: 'multiple_choice',
    prompt: 'Which Spaulding classification applies to instruments that contact intact mucous membranes?',
    options_json: { A: 'Critical', B: 'Semi-critical', C: 'Non-critical', D: 'Minimal risk' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000005',
    category: 'technical',
    type: 'multiple_choice',
    prompt: 'An ethylene oxide (EtO) sterilization cycle requires aeration after the run because:',
    options_json: { A: 'The instruments are too hot to handle', B: 'EtO residuals must off-gas to safe levels before patient contact', C: 'The humidity must normalize', D: 'The cycle indicator needs time to change color' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000006',
    category: 'situational',
    type: 'multiple_choice',
    prompt: 'You receive a tray from the OR with visible bioburden on the instruments. Your first action is:',
    options_json: { A: 'Immediately sterilize the tray to kill the bioburden', B: 'Point-of-use pre-clean, then transport to decontam for full manual cleaning', C: 'Notify your supervisor before touching the tray', D: 'Soak in enzyme solution directly at the sterile assembly table' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000007',
    category: 'situational',
    type: 'multiple_choice',
    prompt: 'During assembly, you find a crack in the hinge of a needle driver. You should:',
    options_json: { A: 'Reassemble the tray — hairline cracks are cosmetic', B: 'Mark the instrument as out of service, set it aside, and document it', C: 'File the crack smooth and return it to service', D: 'Soak in glutaraldehyde to strengthen the joint' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000008',
    category: 'situational',
    type: 'multiple_choice',
    prompt: 'The sterility maintenance time (event-related sterility) for a wrapped tray depends on:',
    options_json: { A: 'The number of days since sterilization', B: 'How the package has been stored and handled since sterilization', C: 'The temperature of the storage area', D: 'The type of sterilizer used' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000009',
    category: 'situational',
    type: 'multiple_choice',
    prompt: 'You accidentally breach your sterile field while opening a peel pouch. The correct action is:',
    options_json: { A: 'Continue — the outer packaging protected the contents', B: 'Discard the item and obtain a new sterile one', C: 'Wipe the item with alcohol and proceed', D: 'Place the item in a sterile basin before using' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000010',
    category: 'situational',
    type: 'multiple_choice',
    prompt: 'A surgeon calls requesting a custom tray not on the standard pick list. You should:',
    options_json: { A: 'Tell them it is impossible without a 24-hour notice', B: 'Check the preference card, verify instrument availability, and communicate an accurate ETA', C: 'Build the tray from memory to save time', D: 'Escalate immediately to the charge nurse without gathering information first' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000011',
    category: 'process',
    type: 'multiple_choice',
    prompt: 'Traceability in sterile processing means:',
    options_json: { A: 'Tracking how many packs were processed per shift', B: 'Linking each sterilized item to the load, sterilizer, operator, date, and patient it was used on', C: 'Verifying that biological indicators are run weekly', D: 'Keeping a log of sterilizer maintenance dates' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000012',
    category: 'process',
    type: 'multiple_choice',
    prompt: 'A chemical integrator inside a sterilization pack that fails to reach pass status indicates:',
    options_json: { A: 'The pack was not sterilized and must be recalled', B: 'Sterilization conditions may not have been met; escalate per your department recall policy', C: 'The sterilizer is malfunctioning and must be taken out of service', D: 'The pack was loaded incorrectly and should be re-wrapped and re-processed immediately' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.25, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000013',
    category: 'process',
    type: 'multiple_choice',
    prompt: 'The ANSI/AAMI ST79 standard is the primary guidance document for:',
    options_json: { A: 'Flexible endoscope reprocessing', B: 'Comprehensive guide to steam sterilization and sterility assurance in health care', C: 'Chemical disinfectant selection and efficacy testing', D: 'Instrument repair and maintenance schedules' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000014',
    category: 'process',
    type: 'multiple_choice',
    prompt: 'When is it acceptable to skip the decontamination step and send an instrument directly to assembly?',
    options_json: { A: 'When the instrument came from a clean procedure', B: 'When the surgeon requests a fast turn', C: 'Never — all used instruments must go through decontam', D: 'Only for non-lumened instruments' },
    scoring_key_json: { correct: 'C', score_map: { A: 0.0, B: 0.0, C: 1.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000015',
    category: 'process',
    type: 'multiple_choice',
    prompt: 'A wet pack is discovered after steam sterilization. The correct action is:',
    options_json: { A: 'Allow it to air dry on the counter', B: 'Reject the pack, investigate the cause, rewrap and re-process', C: 'Use the items immediately — drying time is only needed for shelf storage', D: 'Document it in the log and use the items if the BI was negative' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000016',
    category: 'behavioral',
    type: 'multiple_choice',
    prompt: 'A coworker routinely skips the manual cleaning step when the department is busy. You should:',
    options_json: { A: 'Match their workflow to keep up with volume', B: 'Report them to management anonymously', C: 'Address it professionally with your coworker, then escalate to the supervisor if the behavior continues', D: 'Leave a note in the communication log' },
    scoring_key_json: { correct: 'C', score_map: { A: 0.0, B: 0.25, C: 1.0, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000017',
    category: 'behavioral',
    type: 'multiple_choice',
    prompt: 'During a rush at end of shift, you realize you do not have time to finish a complex tray before handoff. You should:',
    options_json: { A: 'Finish as fast as possible and mark it complete', B: 'Leave the tray where it is without comment', C: 'Communicate the status clearly to the oncoming shift and document where you left off', D: 'Ask a coworker to finish it without telling them the current state' },
    scoring_key_json: { correct: 'C', score_map: { A: 0.0, B: 0.0, C: 1.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000018',
    category: 'behavioral',
    type: 'multiple_choice',
    prompt: 'A new hospital policy requires double-checking instrument counts with a partner before releasing OR sets. Your initial reaction is:',
    options_json: { A: 'This is unnecessary extra work and wastes time', B: 'Implement the policy, recognizing that count checks reduce errors and liability', C: 'Do it only when supervisors are watching', D: 'Ask to be exempt because you have never had a count error' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000019',
    category: 'behavioral',
    type: 'multiple_choice',
    prompt: 'An OR charge nurse tells you a tray you assembled had a wrong instrument count. You should:',
    options_json: { A: 'Deny it — you double-checked the count', B: 'Apologize, take responsibility, investigate your process, and implement a corrective action', C: 'Blame the OR tech who used the tray', D: 'Report it to the OR manager as an OR error' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000020',
    category: 'behavioral',
    type: 'multiple_choice',
    prompt: 'The most important reason to wear full PPE in the decontamination room is:',
    options_json: { A: 'To comply with hospital policy and avoid disciplinary action', B: 'To prevent exposure to bloodborne pathogens and sharps injuries', C: 'Because it makes you look professional', D: 'To keep your uniform clean' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.25, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000021',
    category: 'instrument',
    type: 'multiple_choice',
    prompt: 'A box-lock instrument should be inspected in the OPEN position during assembly because:',
    options_json: { A: 'It is easier to count instruments when open', B: 'Box-lock joints may trap debris and show wear that is invisible when the instrument is closed', C: 'Sterilant does not penetrate closed instruments as effectively', D: 'Instrument strings require open configuration' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000022',
    category: 'instrument',
    type: 'multiple_choice',
    prompt: 'Which of the following instruments is used for blunt dissection and tissue manipulation, not cutting?',
    options_json: { A: 'Metzenbaum scissors', B: 'Kelly hemostat', C: 'Adson forceps', D: '#15 blade scalpel' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000023',
    category: 'instrument',
    type: 'multiple_choice',
    prompt: 'Instruments with tungsten carbide inserts are typically identified by:',
    options_json: { A: 'A gold ring or dot on the handle', B: 'A blue marker on the tip', C: 'A rubber ring at the hinge', D: 'A silver stripe on the shank' },
    scoring_key_json: { correct: 'A', score_map: { A: 1.0, B: 0.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000024',
    category: 'instrument',
    type: 'multiple_choice',
    prompt: 'A preference card for a laparoscopic cholecystectomy lists 5mm trocar x3, 10mm trocar x1. During assembly you find only two 5mm trocars available. You should:',
    options_json: { A: 'Substitute with a 12mm trocar for the third port', B: 'Notify the scheduler and OR nurse, and hold the case tray until the correct count is available or a substitution is approved', C: 'Send the tray with a note saying the third trocar is missing', D: 'Reassign the tray to a different case that needs fewer trocars' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000025',
    category: 'instrument',
    type: 'multiple_choice',
    prompt: 'The purpose of using an ultrasonic cleaner in SPD is:',
    options_json: { A: 'To sterilize instruments at low temperatures', B: 'To use cavitation to remove soil from instrument crevices and lumens that manual cleaning cannot reach', C: 'To replace manual scrubbing for all instruments', D: 'To remove rust and discoloration from stainless steel' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000026',
    category: 'reliability',
    type: 'multiple_choice',
    prompt: 'The SPD department functions on a just-in-time model. Missing a scheduled shift has the most direct impact on:',
    options_json: { A: 'The department overtime budget', B: 'OR case scheduling and patient safety if sterile instruments are unavailable', C: 'Your performance review rating', D: 'Coworker morale' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.25, B: 1.0, C: 0.0, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000027',
    category: 'reliability',
    type: 'multiple_choice',
    prompt: 'You are feeling slightly ill before a shift. The professional action is:',
    options_json: { A: 'Come to work and try to push through', B: 'Call in as soon as possible so staffing can be arranged, and follow your facility illness reporting protocol', C: 'Wait until the shift starts to decide', D: 'Ask a friend to cover informally without notifying the supervisor' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000028',
    category: 'reliability',
    type: 'multiple_choice',
    prompt: 'You are assigned to finish instrument assembly for a trauma set before the end of shift, but you are running low on time. The right approach is:',
    options_json: { A: 'Rush through assembly without checking the count', B: 'Communicate the situation to your supervisor before the deadline, not after', C: 'Leave the tray incomplete and hope the next shift has time', D: 'Skip documentation to save time' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000029',
    category: 'reliability',
    type: 'multiple_choice',
    prompt: 'Your externship site asks you to be available for an extra day next month for a high-volume case day. You:',
    options_json: { A: 'Decline — the externship agreement only covers set hours', B: 'Check your schedule and respond promptly with a clear yes or no', C: 'Say yes but do not confirm via the preferred communication channel', D: 'Ask why you were chosen before deciding' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.25, D: 0.0 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000030',
    category: 'reliability',
    type: 'multiple_choice',
    prompt: 'At the end of your first week, your preceptor gives you corrective feedback on instrument inspection technique. You:',
    options_json: { A: 'Explain that you learned a different method in your training program', B: 'Thank them for the feedback, apply it immediately, and ask a clarifying question if needed', C: 'Nod but continue your original technique', D: 'Report the feedback difference to your program coordinator' },
    scoring_key_json: { correct: 'B', score_map: { A: 0.0, B: 1.0, C: 0.0, D: 0.25 } },
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
]
